import { collection, getDocs, doc, setDoc, serverTimestamp, writeBatch } from 'firebase/firestore';
import { db } from '../lib/firebase';
import { Store, Product, Reservation } from '../types';

export const DEMO_STORES: Store[] = [
  {
    id: 'store_rewe_kleve',
    name: 'REWE Kleve (Demo Partner)',
    ownerId: 'retailer_rewe_kleve',
    address: 'Große Straße 45',
    city: 'Kleve',
    latitude: 51.7885,
    longitude: 6.1362,
    openingHours: 'Mon-Sat 07:00 - 21:30',
    phone: '+49 2821 97810',
    categories: ['Grocery', 'Bakery', 'Drinks'],
    status: 'active',
    imageUrl: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?auto=format&fit=crop&w=800&q=80',
    description: 'Fresh regional produce and daily supermarket goods.',
    pickupInstructions: 'Head to the dedicated Tschüss Pick-up Station near Customer Service.'
  },
  {
    id: 'store_edeka_kleve',
    name: 'EDEKA Center Kleve (Demo Partner)',
    ownerId: 'retailer_edeka_kleve',
    address: 'Ludwig-Jahn-Straße 12',
    city: 'Kleve',
    latitude: 51.7924,
    longitude: 6.1458,
    openingHours: 'Mon-Sat 08:00 - 21:00',
    phone: '+49 2821 72150',
    categories: ['Grocery', 'Drinks', 'Household'],
    status: 'active',
    imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80',
    description: 'Extensive fresh food counters, dairy and produce.',
    pickupInstructions: 'Pick up directly at checkout #1 (express rescue counter).'
  },
  {
    id: 'store_baeckerei_kleve',
    name: 'Bäckerei & Konditorei Kleve (Demo Partner)',
    ownerId: 'retailer_bakery_kleve',
    address: 'Kavarinerstraße 28',
    city: 'Kleve',
    latitude: 51.7869,
    longitude: 6.1340,
    openingHours: 'Mon-Sun 06:30 - 18:00',
    phone: '+49 2821 23411',
    categories: ['Bakery'],
    status: 'active',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
    description: 'Traditional artisan loaves, croissants, and sourdough bread.',
    pickupInstructions: 'Show your Tschüss app code to the counter staff.'
  },
  {
    id: 'store_biomarkt_kleve',
    name: 'BioMarkt Kleve (Demo Partner)',
    ownerId: 'retailer_biomarkt_kleve',
    address: 'Hagsche Straße 82',
    city: 'Kleve',
    latitude: 51.7852,
    longitude: 6.1395,
    openingHours: 'Mon-Fri 08:30 - 19:00, Sat 08:30 - 16:00',
    phone: '+49 2821 45290',
    categories: ['Grocery', 'Cosmetics', 'Drinks'],
    status: 'active',
    imageUrl: 'https://images.unsplash.com/photo-1534723452862-4c874018d66d?auto=format&fit=crop&w=800&q=80',
    description: 'Certified organic dairy, plant-based milks, and natural beauty products.',
    pickupInstructions: 'Proceed to the information desk inside the entrance.'
  },
  {
    id: 'store_blumen_kleve',
    name: 'Blumen & Floristik Kleve (Demo Partner)',
    ownerId: 'retailer_blumen_kleve',
    address: 'Opschlag 14',
    city: 'Kleve',
    latitude: 51.7899,
    longitude: 6.1325,
    openingHours: 'Mon-Sat 08:30 - 18:30',
    phone: '+49 2821 34912',
    categories: ['Flowers'],
    status: 'active',
    imageUrl: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=800&q=80',
    description: 'Seasonal flowers and potted plants rescued before wilting.',
    pickupInstructions: 'Present code at the main florist workstation.'
  },
  {
    id: 'store_aldi_kleve',
    name: 'ALDI SÜD Kleve (Demo Partner)',
    ownerId: 'retailer_aldi_kleve',
    address: 'Emmericher Str. 109',
    city: 'Kleve',
    latitude: 51.7940,
    longitude: 6.1420,
    openingHours: 'Mon-Sat 08:00 - 21:00',
    phone: '+49 2821 89120',
    categories: ['Grocery', 'Drinks', 'Bakery'],
    status: 'active',
    imageUrl: 'https://images.unsplash.com/photo-1578916171728-46686eac8d58?auto=format&fit=crop&w=800&q=80',
    description: 'Surplus bakery, dairy, and seasonal groceries at steep markdowns.',
    pickupInstructions: 'Collect at Checkout #1 with your reservation code.'
  },
  {
    id: 'store_lidl_kleve',
    name: 'Lidl Kleve (Demo Partner)',
    ownerId: 'retailer_lidl_kleve',
    address: 'Flutstraße 34',
    city: 'Kleve',
    latitude: 51.7890,
    longitude: 6.1280,
    openingHours: 'Mon-Sat 07:30 - 21:00',
    phone: '+49 2821 95400',
    categories: ['Grocery', 'Bakery', 'Drinks'],
    status: 'active',
    imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=800&q=80',
    description: 'Daily rescue bakery crates, packaged meals, and dairy specials.',
    pickupInstructions: 'Ask for the Tschüss rescue parcel at the checkout counter.'
  },
  {
    id: 'store_kamps_kleve',
    name: 'Kamps Bäckerei Kleve (Demo Partner)',
    ownerId: 'retailer_kamps_kleve',
    address: 'Hoffmannallee 18',
    city: 'Kleve',
    latitude: 51.7845,
    longitude: 6.1310,
    openingHours: 'Mon-Sat 06:00 - 18:30, Sun 07:30 - 16:00',
    phone: '+49 2821 44520',
    categories: ['Bakery'],
    status: 'active',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
    description: 'Fresh morning rolls, pretzels, muffins, and artisan pastry specials.',
    pickupInstructions: 'Show reservation QR / code to counter barista.'
  },
  {
    id: 'store_denns_kleve',
    name: 'Denns Biomarkt Kleve (Demo Partner)',
    ownerId: 'retailer_denns_kleve',
    address: 'Tiergartenstraße 4',
    city: 'Kleve',
    latitude: 51.7915,
    longitude: 6.1375,
    openingHours: 'Mon-Sat 08:00 - 20:00',
    phone: '+49 2821 66890',
    categories: ['Grocery', 'Drinks', 'Cosmetics'],
    status: 'active',
    imageUrl: 'https://images.unsplash.com/photo-1534723452862-4c874018d66d?auto=format&fit=crop&w=800&q=80',
    description: 'Certified organic dairy, fresh greens, plant milks, and kombucha.',
    pickupInstructions: 'Pickup at the organic deli counter.'
  },
  {
    id: 'store_feinkost_kleve',
    name: 'Klever Feinkost & Delikatessen (Demo Partner)',
    ownerId: 'retailer_feinkost_kleve',
    address: 'Herzogstraße 8',
    city: 'Kleve',
    latitude: 51.7878,
    longitude: 6.1350,
    openingHours: 'Mon-Fri 09:00 - 19:00, Sat 09:00 - 17:00',
    phone: '+49 2821 31200',
    categories: ['Grocery', 'Bakery'],
    status: 'active',
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?auto=format&fit=crop&w=800&q=80',
    description: 'Fine European cheeses, gourmet sandwiches, antipasti, and charcuterie.',
    pickupInstructions: 'Present reservation code at the charcuterie desk.'
  }
];

// Helper to generate dynamic dates relative to current time
export const getFutureDate = (hoursFromNow: number) => {
  const date = new Date(Date.now() + hoursFromNow * 3600 * 1000);
  return date.toISOString();
};

export function getFreshDemoProducts(): Product[] {
  return DEMO_PRODUCTS.map((p, idx) => {
    // Generate realistic staggered active expiry offsets (14h to 48h in future)
    const hours = 14 + ((idx * 5) % 36);
    return {
      ...p,
      expiryAt: getFutureDate(hours),
      status: p.status || 'active',
      quantityAvailable: p.quantityAvailable > 0 ? p.quantityAvailable : 5
    };
  });
}

export const DEMO_PRODUCTS: Product[] = [
  {
    id: 'prod_creamy_yoghurt',
    storeId: 'store_rewe_kleve',
    storeName: 'REWE Kleve (Demo Partner)',
    storeAddress: 'Große Straße 45, Kleve',
    storeCity: 'Kleve',
    storeLat: 51.7885,
    storeLng: 6.1362,
    name: 'Creamy Greek Style Yoghurt 500g',
    description: 'Full-bodied organic yoghurt with authentic mild culture. Perfectly fresh and chilled.',
    category: 'Grocery',
    imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=800&q=80',
    originalPrice: 2.50,
    discountPercent: 70,
    rescuePrice: 0.75,
    quantityAvailable: 5,
    unit: '500g tub',
    expiryAt: getFutureDate(26), // Tomorrow
    pickupStartTime: '08:00',
    pickupEndTime: '21:00',
    status: 'active',
    estimatedWeightKg: 0.5
  },
  {
    id: 'prod_wholegrain_bread',
    storeId: 'store_baeckerei_kleve',
    storeName: 'Bäckerei & Konditorei Kleve (Demo Partner)',
    storeAddress: 'Kavarinerstraße 28, Kleve',
    storeCity: 'Kleve',
    storeLat: 51.7869,
    storeLng: 6.1340,
    name: 'Artisan Wholegrain Sourdough Loaf',
    description: 'Stone-oven baked sourdough with sunflower and pumpkin seeds. Baked this morning.',
    category: 'Bakery',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
    originalPrice: 3.80,
    discountPercent: 65,
    rescuePrice: 1.33,
    quantityAvailable: 8,
    unit: '750g loaf',
    expiryAt: getFutureDate(18), // Tomorrow morning
    pickupStartTime: '14:00',
    pickupEndTime: '18:00',
    status: 'active',
    estimatedWeightKg: 0.75
  },
  {
    id: 'prod_tulip_bouquet',
    storeId: 'store_blumen_kleve',
    storeName: 'Blumen & Floristik Kleve (Demo Partner)',
    storeAddress: 'Opschlag 14, Kleve',
    storeCity: 'Kleve',
    storeLat: 51.7899,
    storeLng: 6.1325,
    name: 'Fresh Tulip Bouquet (15 stems)',
    description: 'Vibrant spring tulips in bloom. Still fresh for 4-5 days of vase life at home.',
    category: 'Flowers',
    imageUrl: 'https://images.unsplash.com/photo-1520763185298-1b434c919102?auto=format&fit=crop&w=800&q=80',
    originalPrice: 12.00,
    discountPercent: 70,
    rescuePrice: 3.60,
    quantityAvailable: 4,
    unit: 'bunch',
    expiryAt: getFutureDate(14), // Today evening
    pickupStartTime: '10:00',
    pickupEndTime: '18:30',
    status: 'active',
    estimatedWeightKg: 0.4
  },
  {
    id: 'prod_bio_oat_milk',
    storeId: 'store_biomarkt_kleve',
    storeName: 'BioMarkt Kleve (Demo Partner)',
    storeAddress: 'Hagsche Straße 82, Kleve',
    storeCity: 'Kleve',
    storeLat: 51.7852,
    storeLng: 6.1395,
    name: 'Organic Barista Oat Drink (1L)',
    description: 'Creamy plant-based oat beverage ideal for specialty coffee foam and breakfast cereal.',
    category: 'Drinks',
    imageUrl: 'https://images.unsplash.com/photo-1556881286-fc6915169721?auto=format&fit=crop&w=800&q=80',
    originalPrice: 2.29,
    discountPercent: 55,
    rescuePrice: 1.03,
    quantityAvailable: 12,
    unit: '1L carton',
    expiryAt: getFutureDate(48), // in 2 days
    pickupStartTime: '09:00',
    pickupEndTime: '19:00',
    status: 'active',
    estimatedWeightKg: 1.0
  },
  {
    id: 'prod_face_cream',
    storeId: 'store_biomarkt_kleve',
    storeName: 'BioMarkt Kleve (Demo Partner)',
    storeAddress: 'Hagsche Straße 82, Kleve',
    storeCity: 'Kleve',
    storeLat: 51.7852,
    storeLng: 6.1395,
    name: 'Soothing Chamomile Night Cream 50ml',
    description: 'Gentle certified natural cosmetic formula. Near best-before date but sealed and pristine.',
    category: 'Cosmetics',
    imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80',
    originalPrice: 9.50,
    discountPercent: 60,
    rescuePrice: 3.80,
    quantityAvailable: 3,
    unit: '50ml jar',
    expiryAt: getFutureDate(72), // in 3 days
    pickupStartTime: '09:00',
    pickupEndTime: '19:00',
    status: 'active',
    estimatedWeightKg: 0.15
  },
  {
    id: 'prod_crisp_apples',
    storeId: 'store_edeka_kleve',
    storeName: 'EDEKA Center Kleve (Demo Partner)',
    storeAddress: 'Ludwig-Jahn-Straße 12, Kleve',
    storeCity: 'Kleve',
    storeLat: 51.7924,
    storeLng: 6.1458,
    name: 'Regional Elstar Apples (1.5 kg bag)',
    description: 'Crisp and juicy sweet-tart apples from local Lower Rhine orchards.',
    category: 'Grocery',
    imageUrl: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=800&q=80',
    originalPrice: 3.49,
    discountPercent: 70,
    rescuePrice: 1.05,
    quantityAvailable: 7,
    unit: '1.5 kg bag',
    expiryAt: getFutureDate(30), // tomorrow
    pickupStartTime: '08:00',
    pickupEndTime: '20:30',
    status: 'active',
    estimatedWeightKg: 1.5
  },
  {
    id: 'prod_french_croissants',
    storeId: 'store_baeckerei_kleve',
    storeName: 'Bäckerei & Konditorei Kleve (Demo Partner)',
    storeAddress: 'Kavarinerstraße 28, Kleve',
    storeCity: 'Kleve',
    storeLat: 51.7869,
    storeLng: 6.1340,
    name: 'Butter Croissants 4-Pack',
    description: 'Flaky pure butter croissants freshly baked. Delicious warmed up or with jam.',
    category: 'Bakery',
    imageUrl: 'https://images.unsplash.com/photo-1555507036-ab1f4038808a?auto=format&fit=crop&w=800&q=80',
    originalPrice: 4.20,
    discountPercent: 70,
    rescuePrice: 1.26,
    quantityAvailable: 6,
    unit: '4 pack',
    expiryAt: getFutureDate(12), // Today
    pickupStartTime: '15:00',
    pickupEndTime: '18:00',
    status: 'active',
    estimatedWeightKg: 0.35
  },
  {
    id: 'prod_organic_orange_juice',
    storeId: 'store_rewe_kleve',
    storeName: 'REWE Kleve (Demo Partner)',
    storeAddress: 'Große Straße 45, Kleve',
    storeCity: 'Kleve',
    storeLat: 51.7885,
    storeLng: 6.1362,
    name: 'Direct Squeezed Bio Orange Juice 1L',
    description: 'Fresh non-concentrated organic orange juice with pulp. High vitamin C.',
    category: 'Drinks',
    imageUrl: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=800&q=80',
    originalPrice: 2.89,
    discountPercent: 60,
    rescuePrice: 1.16,
    quantityAvailable: 9,
    unit: '1L glass bottle',
    expiryAt: getFutureDate(38),
    pickupStartTime: '08:00',
    pickupEndTime: '21:00',
    status: 'active',
    estimatedWeightKg: 1.1
  },
  {
    id: 'prod_belgian_lava_cake',
    storeId: 'store_rewe_kleve',
    storeName: 'REWE Kleve (Demo Partner)',
    storeAddress: 'Große Straße 45, Kleve',
    storeCity: 'Kleve',
    storeLat: 51.7885,
    storeLng: 6.1362,
    name: 'Belgian Molten Chocolate Lava Cake (2-Pack)',
    description: 'Decadent dark chocolate molten center fondant cakes. Warm for 20 seconds in microwave for melting core.',
    category: 'Grocery',
    imageUrl: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=800&q=80',
    originalPrice: 4.49,
    discountPercent: 67,
    rescuePrice: 1.49,
    quantityAvailable: 6,
    unit: '2x 100g pack',
    expiryAt: getFutureDate(24),
    pickupStartTime: '08:00',
    pickupEndTime: '21:00',
    status: 'active',
    estimatedWeightKg: 0.22
  },
  {
    id: 'prod_crispy_chicken_tenders',
    storeId: 'store_edeka_kleve',
    storeName: 'EDEKA Center Kleve (Demo Partner)',
    storeAddress: 'Ludwig-Jahn-Straße 12, Kleve',
    storeCity: 'Kleve',
    storeLat: 51.7924,
    storeLng: 6.1458,
    name: 'Crispy Golden Chicken Finger Bites & Honey Dip',
    description: 'Tender chicken breast fillets with crispy panko breading and sweet chili honey sauce from the deli counter.',
    category: 'Grocery',
    imageUrl: 'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=800&q=80',
    originalPrice: 4.99,
    discountPercent: 60,
    rescuePrice: 1.99,
    quantityAvailable: 4,
    unit: '350g box',
    expiryAt: getFutureDate(14),
    pickupStartTime: '11:00',
    pickupEndTime: '20:30',
    status: 'active',
    estimatedWeightKg: 0.38
  },
  {
    id: 'prod_sushi_box',
    storeId: 'store_rewe_kleve',
    storeName: 'REWE Kleve (Demo Partner)',
    storeAddress: 'Große Straße 45, Kleve',
    storeCity: 'Kleve',
    storeLat: 51.7885,
    storeLng: 6.1362,
    name: 'Tokyo Salmon & Tuna Maki Nigiri Combo (12 pcs)',
    description: 'Handcrafted sushi combo with fresh Atlantic salmon, yellowfin tuna nigiri, avocado maki, ginger, and wasabi.',
    category: 'Grocery',
    imageUrl: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=800&q=80',
    originalPrice: 9.90,
    discountPercent: 65,
    rescuePrice: 3.45,
    quantityAvailable: 5,
    unit: '12 pcs tray',
    expiryAt: getFutureDate(10),
    pickupStartTime: '14:00',
    pickupEndTime: '21:00',
    status: 'active',
    estimatedWeightKg: 0.32
  },
  {
    id: 'prod_truffle_pizza',
    storeId: 'store_rewe_kleve',
    storeName: 'REWE Kleve (Demo Partner)',
    storeAddress: 'Große Straße 45, Kleve',
    storeCity: 'Kleve',
    storeLat: 51.7885,
    storeLng: 6.1362,
    name: 'Stonebaked Truffle & Portobello Mushroom Pizza',
    description: 'Authentic stonebaked sourdough pizza topped with aromatic black truffle cream, roasted portobello, and fior di latte.',
    category: 'Grocery',
    imageUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=800&q=80',
    originalPrice: 5.49,
    discountPercent: 66,
    rescuePrice: 1.85,
    quantityAvailable: 7,
    unit: '420g pizza',
    expiryAt: getFutureDate(28),
    pickupStartTime: '08:00',
    pickupEndTime: '21:00',
    status: 'active',
    estimatedWeightKg: 0.45
  },
  {
    id: 'prod_mediterranean_antipasti',
    storeId: 'store_edeka_kleve',
    storeName: 'EDEKA Center Kleve (Demo Partner)',
    storeAddress: 'Ludwig-Jahn-Straße 12, Kleve',
    storeCity: 'Kleve',
    storeLat: 51.7924,
    storeLng: 6.1458,
    name: 'Mediterranean Antipasti Mix with Kalamata Olives',
    description: 'Marinated Greek Kalamata olives, sun-dried tomatoes, stuffed mild peppadew peppers, and herb infused olive oil.',
    category: 'Grocery',
    imageUrl: 'https://images.unsplash.com/photo-1541529086526-db283c563270?auto=format&fit=crop&w=800&q=80',
    originalPrice: 3.79,
    discountPercent: 66,
    rescuePrice: 1.30,
    quantityAvailable: 6,
    unit: '250g deli tub',
    expiryAt: getFutureDate(42),
    pickupStartTime: '08:00',
    pickupEndTime: '20:30',
    status: 'active',
    estimatedWeightKg: 0.28
  },
  {
    id: 'prod_bavarian_pretzels',
    storeId: 'store_kamps_kleve',
    storeName: 'Kamps Bäckerei Kleve (Demo Partner)',
    storeAddress: 'Hoffmannallee 18, Kleve',
    storeCity: 'Kleve',
    storeLat: 51.7845,
    storeLng: 6.1310,
    name: 'Bavarian Butter Pretzels (3 pcs)',
    description: 'Traditional Bavarian lye pretzels with coarse sea salt crystals and rich butter layering. Baked fresh today.',
    category: 'Bakery',
    imageUrl: 'https://images.unsplash.com/photo-1534432182912-63863115e106?auto=format&fit=crop&w=800&q=80',
    originalPrice: 2.85,
    discountPercent: 67,
    rescuePrice: 0.95,
    quantityAvailable: 8,
    unit: '3 pcs bag',
    expiryAt: getFutureDate(11),
    pickupStartTime: '12:00',
    pickupEndTime: '18:30',
    status: 'active',
    estimatedWeightKg: 0.3
  },
  {
    id: 'prod_french_baguettes',
    storeId: 'store_baeckerei_kleve',
    storeName: 'Bäckerei & Konditorei Kleve (Demo Partner)',
    storeAddress: 'Kavarinerstraße 28, Kleve',
    storeCity: 'Kleve',
    storeLat: 51.7869,
    storeLng: 6.1340,
    name: 'French Stone-Oven Baguettes (2-Pack)',
    description: 'Crisp golden crust with airy, open crumb structure. Baked with French flour according to traditional Parisian recipe.',
    category: 'Bakery',
    imageUrl: 'https://images.unsplash.com/photo-1589367920969-ab8e050bbb04?auto=format&fit=crop&w=800&q=80',
    originalPrice: 2.60,
    discountPercent: 67,
    rescuePrice: 0.85,
    quantityAvailable: 10,
    unit: '2 baguettes',
    expiryAt: getFutureDate(14),
    pickupStartTime: '14:00',
    pickupEndTime: '18:00',
    status: 'active',
    estimatedWeightKg: 0.5
  },
  {
    id: 'prod_cinnamon_franzbroetchen',
    storeId: 'store_kamps_kleve',
    storeName: 'Kamps Bäckerei Kleve (Demo Partner)',
    storeAddress: 'Hoffmannallee 18, Kleve',
    storeCity: 'Kleve',
    storeLat: 51.7845,
    storeLng: 6.1310,
    name: 'Hamburg Cinnamon Franzbrötchen (2 pcs)',
    description: 'Buttery flaky pastry swirled with aromatic Ceylon cinnamon and caramelized brown sugar crust.',
    category: 'Bakery',
    imageUrl: 'https://images.unsplash.com/photo-1509365465985-25d11c17e812?auto=format&fit=crop&w=800&q=80',
    originalPrice: 3.20,
    discountPercent: 66,
    rescuePrice: 1.10,
    quantityAvailable: 6,
    unit: '2 pcs pack',
    expiryAt: getFutureDate(15),
    pickupStartTime: '11:00',
    pickupEndTime: '18:30',
    status: 'active',
    estimatedWeightKg: 0.22
  },
  {
    id: 'prod_camembert_cheese',
    storeId: 'store_edeka_kleve',
    storeName: 'EDEKA Center Kleve (Demo Partner)',
    storeAddress: 'Ludwig-Jahn-Straße 12, Kleve',
    storeCity: 'Kleve',
    storeLat: 51.7924,
    storeLng: 6.1458,
    name: 'French Camembert de Normandie AOC 250g',
    description: 'Creamy soft bloomy rind raw milk cheese from Normandy. Rich earthy hazelnut aroma, perfectly ripe.',
    category: 'Grocery',
    imageUrl: 'https://images.unsplash.com/photo-1452195100486-9cc805987862?auto=format&fit=crop&w=800&q=80',
    originalPrice: 3.99,
    discountPercent: 65,
    rescuePrice: 1.40,
    quantityAvailable: 5,
    unit: '250g wooden box',
    expiryAt: getFutureDate(36),
    pickupStartTime: '08:00',
    pickupEndTime: '20:30',
    status: 'active',
    estimatedWeightKg: 0.27
  },
  {
    id: 'prod_burrata_pugliese',
    storeId: 'store_rewe_kleve',
    storeName: 'REWE Kleve (Demo Partner)',
    storeAddress: 'Große Straße 45, Kleve',
    storeCity: 'Kleve',
    storeLat: 51.7885,
    storeLng: 6.1362,
    name: 'Italian Burrata Pugliese in Brine 200g',
    description: 'Silky mozzarella pouch bursting with rich creamy stracciatella. Best enjoyed with tomatoes and olive oil.',
    category: 'Grocery',
    imageUrl: 'https://images.unsplash.com/photo-1592417817098-8f3d69102a56?auto=format&fit=crop&w=800&q=80',
    originalPrice: 3.69,
    discountPercent: 66,
    rescuePrice: 1.25,
    quantityAvailable: 7,
    unit: '200g tub',
    expiryAt: getFutureDate(30),
    pickupStartTime: '08:00',
    pickupEndTime: '21:00',
    status: 'active',
    estimatedWeightKg: 0.25
  },
  {
    id: 'prod_falafel_bowl',
    storeId: 'store_biomarkt_kleve',
    storeName: 'BioMarkt Kleve (Demo Partner)',
    storeAddress: 'Hagsche Straße 82, Kleve',
    storeCity: 'Kleve',
    storeLat: 51.7852,
    storeLng: 6.1395,
    name: 'Organic Falafel Hummus Buddha Bowl 380g',
    description: 'Crispy herb falafel patties, creamy tahini hummus, roasted sweet potatoes, quinoa, and pickled pomegranate.',
    category: 'Grocery',
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=800&q=80',
    originalPrice: 6.20,
    discountPercent: 65,
    rescuePrice: 2.15,
    quantityAvailable: 5,
    unit: '380g bowl',
    expiryAt: getFutureDate(18),
    pickupStartTime: '11:00',
    pickupEndTime: '19:00',
    status: 'active',
    estimatedWeightKg: 0.4
  },
  {
    id: 'prod_strawberries_500g',
    storeId: 'store_aldi_kleve',
    storeName: 'ALDI SÜD Kleve (Demo Partner)',
    storeAddress: 'Emmericher Str. 109, Kleve',
    storeCity: 'Kleve',
    storeLat: 51.7940,
    storeLng: 6.1420,
    name: 'Sweet Garden Strawberries 500g',
    description: 'Sun-ripened regional strawberries with vibrant aroma and natural sweetness. Great for snacking or desserts.',
    category: 'Grocery',
    imageUrl: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?auto=format&fit=crop&w=800&q=80',
    originalPrice: 3.29,
    discountPercent: 70,
    rescuePrice: 0.99,
    quantityAvailable: 11,
    unit: '500g punnet',
    expiryAt: getFutureDate(20),
    pickupStartTime: '08:00',
    pickupEndTime: '20:30',
    status: 'active',
    estimatedWeightKg: 0.52
  },
  {
    id: 'prod_hass_avocados',
    storeId: 'store_biomarkt_kleve',
    storeName: 'BioMarkt Kleve (Demo Partner)',
    storeAddress: 'Hagsche Straße 82, Kleve',
    storeCity: 'Kleve',
    storeLat: 51.7852,
    storeLng: 6.1395,
    name: 'Ripe & Ready Hass Avocados (Pack of 3)',
    description: 'Creamy buttery Hass avocados at peak eating ripeness. Ideal for homemade guacamole or salad bowls.',
    category: 'Grocery',
    imageUrl: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&w=800&q=80',
    originalPrice: 3.49,
    discountPercent: 66,
    rescuePrice: 1.20,
    quantityAvailable: 8,
    unit: '3-pack net',
    expiryAt: getFutureDate(22),
    pickupStartTime: '09:00',
    pickupEndTime: '19:00',
    status: 'active',
    estimatedWeightKg: 0.6
  },
  {
    id: 'prod_cherry_tomatoes',
    storeId: 'store_aldi_kleve',
    storeName: 'ALDI SÜD Kleve (Demo Partner)',
    storeAddress: 'Emmericher Str. 109, Kleve',
    storeCity: 'Kleve',
    storeLat: 51.7940,
    storeLng: 6.1420,
    name: 'Sweet Vine Cherry Tomatoes 400g',
    description: 'Aromatic vine-ripened red cherry tomatoes with crisp skin and juicy sweet flavor.',
    category: 'Grocery',
    imageUrl: 'https://images.unsplash.com/photo-1546470427-0d4db154ceb7?auto=format&fit=crop&w=800&q=80',
    originalPrice: 2.49,
    discountPercent: 68,
    rescuePrice: 0.79,
    quantityAvailable: 9,
    unit: '400g vine tray',
    expiryAt: getFutureDate(26),
    pickupStartTime: '08:00',
    pickupEndTime: '20:30',
    status: 'active',
    estimatedWeightKg: 0.42
  },
  {
    id: 'prod_spinach_mix',
    storeId: 'store_denns_kleve',
    storeName: 'Denns Biomarkt Kleve (Demo Partner)',
    storeAddress: 'Tiergartenstraße 4, Kleve',
    storeCity: 'Kleve',
    storeLat: 51.7915,
    storeLng: 6.1375,
    name: 'Organic Young Baby Spinach & Rocket Salad 200g',
    description: 'Tender baby spinach leaves and peppery wild rocket, washed and ready to toss with dressing.',
    category: 'Grocery',
    imageUrl: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=800&q=80',
    originalPrice: 2.19,
    discountPercent: 66,
    rescuePrice: 0.75,
    quantityAvailable: 7,
    unit: '200g bag',
    expiryAt: getFutureDate(16),
    pickupStartTime: '08:30',
    pickupEndTime: '20:00',
    status: 'active',
    estimatedWeightKg: 0.22
  },
  {
    id: 'prod_tortellini_ricotta',
    storeId: 'store_lidl_kleve',
    storeName: 'Lidl Kleve (Demo Partner)',
    storeAddress: 'Flutstraße 34, Kleve',
    storeCity: 'Kleve',
    storeLat: 51.7890,
    storeLng: 6.1280,
    name: 'Handmade Spinach & Ricotta Tortellini Pasta 400g',
    description: 'Egg pasta parcels filled with creamy Italian ricotta cheese and sautéed spinach. Cooks in 3 minutes.',
    category: 'Grocery',
    imageUrl: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=800&q=80',
    originalPrice: 2.79,
    discountPercent: 66,
    rescuePrice: 0.95,
    quantityAvailable: 8,
    unit: '400g chilled pack',
    expiryAt: getFutureDate(32),
    pickupStartTime: '08:00',
    pickupEndTime: '21:00',
    status: 'active',
    estimatedWeightKg: 0.42
  },
  {
    id: 'prod_chocolate_muffins',
    storeId: 'store_kamps_kleve',
    storeName: 'Kamps Bäckerei Kleve (Demo Partner)',
    storeAddress: 'Hoffmannallee 18, Kleve',
    storeCity: 'Kleve',
    storeLat: 51.7845,
    storeLng: 6.1310,
    name: 'Dark Double Chocolate Chunk Muffins (2-Pack)',
    description: 'Moist cocoa sponge muffins generously loaded with Belgian dark and milk chocolate melting chunks.',
    category: 'Bakery',
    imageUrl: 'https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?auto=format&fit=crop&w=800&q=80',
    originalPrice: 3.50,
    discountPercent: 66,
    rescuePrice: 1.20,
    quantityAvailable: 6,
    unit: '2 muffins box',
    expiryAt: getFutureDate(18),
    pickupStartTime: '11:00',
    pickupEndTime: '18:30',
    status: 'active',
    estimatedWeightKg: 0.26
  },
  {
    id: 'prod_artisan_panini',
    storeId: 'store_feinkost_kleve',
    storeName: 'Klever Feinkost & Delikatessen (Demo Partner)',
    storeAddress: 'Herzogstraße 8, Kleve',
    storeCity: 'Kleve',
    storeLat: 51.7878,
    storeLng: 6.1350,
    name: 'Smoked Ham & Aged Gouda Artisan Panini',
    description: 'Herb focaccia pressed with Westphalian smoked ham, 18-month aged Gouda, dijon spread, and baby greens.',
    category: 'Grocery',
    imageUrl: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=800&q=80',
    originalPrice: 4.80,
    discountPercent: 67,
    rescuePrice: 1.60,
    quantityAvailable: 5,
    unit: '1 gourmet panini',
    expiryAt: getFutureDate(12),
    pickupStartTime: '11:30',
    pickupEndTime: '17:00',
    status: 'active',
    estimatedWeightKg: 0.3
  },
  {
    id: 'prod_grassfed_butter',
    storeId: 'store_aldi_kleve',
    storeName: 'ALDI SÜD Kleve (Demo Partner)',
    storeAddress: 'Emmericher Str. 109, Kleve',
    storeCity: 'Kleve',
    storeLat: 51.7940,
    storeLng: 6.1420,
    name: 'Irish Salted Grass-Fed Alpine Butter 250g',
    description: 'Rich golden traditional Irish butter made from summer pasture grass-fed cows. Natural sea salt touch.',
    category: 'Grocery',
    imageUrl: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&w=800&q=80',
    originalPrice: 2.89,
    discountPercent: 60,
    rescuePrice: 1.15,
    quantityAvailable: 10,
    unit: '250g foil wrap',
    expiryAt: getFutureDate(44),
    pickupStartTime: '08:00',
    pickupEndTime: '20:30',
    status: 'active',
    estimatedWeightKg: 0.26
  },
  {
    id: 'prod_cold_brew_coffee',
    storeId: 'store_rewe_kleve',
    storeName: 'REWE Kleve (Demo Partner)',
    storeAddress: 'Große Straße 45, Kleve',
    storeCity: 'Kleve',
    storeLat: 51.7885,
    storeLng: 6.1362,
    name: 'Cold Brew Madagascar Vanilla Coffee 330ml',
    description: 'Steeped for 18 hours using 100% Arabica beans with a touch of Madagascar bourbon vanilla and almond milk.',
    category: 'Drinks',
    imageUrl: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?auto=format&fit=crop&w=800&q=80',
    originalPrice: 2.69,
    discountPercent: 63,
    rescuePrice: 0.99,
    quantityAvailable: 8,
    unit: '330ml bottle',
    expiryAt: getFutureDate(36),
    pickupStartTime: '08:00',
    pickupEndTime: '21:00',
    status: 'active',
    estimatedWeightKg: 0.35
  },
  {
    id: 'prod_sparkling_kombucha',
    storeId: 'store_denns_kleve',
    storeName: 'Denns Biomarkt Kleve (Demo Partner)',
    storeAddress: 'Tiergartenstraße 4, Kleve',
    storeCity: 'Kleve',
    storeLat: 51.7915,
    storeLng: 6.1375,
    name: 'Organic Ginger & Lime Sparkling Kombucha 330ml',
    description: 'Fermented live culture raw tea drink infused with cold-pressed ginger and zesty Persian lime juice.',
    category: 'Drinks',
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=800&q=80',
    originalPrice: 2.99,
    discountPercent: 63,
    rescuePrice: 1.10,
    quantityAvailable: 9,
    unit: '330ml glass bottle',
    expiryAt: getFutureDate(40),
    pickupStartTime: '08:30',
    pickupEndTime: '20:00',
    status: 'active',
    estimatedWeightKg: 0.45
  },
  {
    id: 'prod_mango_smoothie',
    storeId: 'store_edeka_kleve',
    storeName: 'EDEKA Center Kleve (Demo Partner)',
    storeAddress: 'Ludwig-Jahn-Straße 12, Kleve',
    storeCity: 'Kleve',
    storeLat: 51.7924,
    storeLng: 6.1458,
    name: 'Pure Mango, Passionfruit & Orange Smoothie 750ml',
    description: 'Thick velvety smoothie pressed from Alphonso mangoes, purple passionfruit, and sweet oranges. 100% fruit.',
    category: 'Drinks',
    imageUrl: 'https://images.unsplash.com/photo-1553530666-ba11a7da3888?auto=format&fit=crop&w=800&q=80',
    originalPrice: 3.49,
    discountPercent: 64,
    rescuePrice: 1.25,
    quantityAvailable: 6,
    unit: '750ml bottle',
    expiryAt: getFutureDate(24),
    pickupStartTime: '08:00',
    pickupEndTime: '20:30',
    status: 'active',
    estimatedWeightKg: 0.8
  },
  {
    id: 'prod_aged_gouda',
    storeId: 'store_feinkost_kleve',
    storeName: 'Klever Feinkost & Delikatessen (Demo Partner)',
    storeAddress: 'Herzogstraße 8, Kleve',
    storeCity: 'Kleve',
    storeLat: 51.7878,
    storeLng: 6.1350,
    name: 'Dutch Aged Gouda Wedges (18 Months Old) 300g',
    description: 'Deep savory Dutch farmstead Gouda with delicate crunchy tyrosine crystals and rich caramel notes.',
    category: 'Grocery',
    imageUrl: 'https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?auto=format&fit=crop&w=800&q=80',
    originalPrice: 5.80,
    discountPercent: 66,
    rescuePrice: 1.95,
    quantityAvailable: 6,
    unit: '300g wedge',
    expiryAt: getFutureDate(48),
    pickupStartTime: '09:00',
    pickupEndTime: '17:00',
    status: 'active',
    estimatedWeightKg: 0.32
  },
  {
    id: 'prod_rustic_bread_rolls',
    storeId: 'store_baeckerei_kleve',
    storeName: 'Bäckerei & Konditorei Kleve (Demo Partner)',
    storeAddress: 'Kavarinerstraße 28, Kleve',
    storeCity: 'Kleve',
    storeLat: 51.7869,
    storeLng: 6.1340,
    name: 'Mixed Crusty Bread Rolls (Bag of 6)',
    description: 'Crisp German morning rolls: rye rolls, poppyseed rolls, sesame rolls, and sunflower seed crust rolls.',
    category: 'Bakery',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
    originalPrice: 3.00,
    discountPercent: 70,
    rescuePrice: 0.90,
    quantityAvailable: 12,
    unit: 'bag of 6',
    expiryAt: getFutureDate(13),
    pickupStartTime: '13:00',
    pickupEndTime: '18:00',
    status: 'active',
    estimatedWeightKg: 0.45
  }
];

export const DEMO_RESERVATIONS: Reservation[] = [
  {
    id: 'res_demo_001',
    reservationCode: 'TS-4829',
    consumerId: 'demo_consumer_123',
    consumerName: 'Hannah Becker',
    consumerEmail: 'hannah.consumer@tschuess.de',
    consumerPhone: '+49 2821 789012',
    storeId: 'store_rewe_kleve',
    storeName: 'REWE Kleve (Demo Partner)',
    storeAddress: 'Große Straße 45, Kleve',
    storePhone: '+49 2821 97810',
    storeLat: 51.7885,
    storeLng: 6.1362,
    items: [
      {
        productId: 'prod_creamy_yoghurt',
        name: 'Creamy Greek Style Yoghurt 500g',
        imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=800&q=80',
        originalPrice: 2.50,
        rescuePrice: 0.75,
        quantity: 2,
        total: 1.50,
        category: 'Grocery',
        estimatedWeightKg: 0.5
      }
    ],
    totalAmount: 1.50,
    totalSaved: 3.50,
    totalWeightKg: 1.0,
    pickupWindow: 'Today 17:00 - 20:30',
    pickupDeadline: 'Today 20:30',
    status: 'READY',
    createdAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 3600 * 1000).toISOString()
  },
  {
    id: 'res_demo_002',
    reservationCode: 'TS-3914',
    consumerId: 'demo_consumer_123',
    consumerName: 'Hannah Becker',
    consumerEmail: 'hannah.consumer@tschuess.de',
    consumerPhone: '+49 2821 789012',
    storeId: 'store_baeckerei_kleve',
    storeName: 'Bäckerei & Konditorei Kleve (Demo Partner)',
    storeAddress: 'Kavarinerstraße 28, Kleve',
    storePhone: '+49 2821 23411',
    storeLat: 51.7869,
    storeLng: 6.1340,
    items: [
      {
        productId: 'prod_wholegrain_bread',
        name: 'Artisan Wholegrain Sourdough Loaf',
        imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=800&q=80',
        originalPrice: 3.80,
        rescuePrice: 1.33,
        quantity: 1,
        total: 1.33,
        category: 'Bakery',
        estimatedWeightKg: 0.75
      }
    ],
    totalAmount: 1.33,
    totalSaved: 2.47,
    totalWeightKg: 0.75,
    pickupWindow: 'Yesterday 16:00 - 18:00',
    pickupDeadline: 'Yesterday 18:00',
    status: 'COLLECTED',
    createdAt: new Date(Date.now() - 28 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    collectedAt: new Date(Date.now() - 24 * 3600 * 1000).toISOString()
  },
  {
    id: 'res_demo_003',
    reservationCode: 'TS-7721',
    consumerId: 'demo_consumer_123',
    consumerName: 'Hannah Becker',
    consumerEmail: 'hannah.consumer@tschuess.de',
    consumerPhone: '+49 2821 789012',
    storeId: 'store_biomarkt_kleve',
    storeName: 'BioMarkt Kleve Organics (Demo Partner)',
    storeAddress: 'Hagsche Straße 12, Kleve',
    storePhone: '+49 2821 56712',
    storeLat: 51.7891,
    storeLng: 6.1385,
    items: [
      {
        productId: 'prod_avocado_bag',
        name: 'Ready-to-Eat Hass Avocados (Pack of 3)',
        imageUrl: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&w=800&q=80',
        originalPrice: 3.49,
        rescuePrice: 1.20,
        quantity: 1,
        total: 1.20,
        category: 'Grocery',
        estimatedWeightKg: 0.6
      }
    ],
    totalAmount: 1.20,
    totalSaved: 2.29,
    totalWeightKg: 0.6,
    pickupWindow: 'Today 18:00 - 21:00',
    pickupDeadline: 'Today 21:00',
    status: 'CONFIRMED',
    // Created 3 minutes ago -> ~7 minutes left of 10-minute cancellation window
    createdAt: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 3 * 60 * 1000).toISOString()
  }
];

/**
 * Seeds the Firestore database with initial realistic demo stores, products, and sample reservations if not present.
 */
export async function seedDemoDataIfEmpty(): Promise<{ seeded: boolean; message: string }> {
  try {
    const productsSnap = await getDocs(collection(db, 'products'));
    if (!productsSnap.empty) {
      return { seeded: false, message: 'Database already contains products.' };
    }

    const freshProducts = getFreshDemoProducts();

    // Seed Stores
    for (const store of DEMO_STORES) {
      await setDoc(doc(db, 'stores', store.id), {
        ...store,
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp()
      }, { merge: true });
    }

    // Seed Products with fresh future active expiry dates
    for (const product of freshProducts) {
      await setDoc(doc(db, 'products', product.id), {
        ...product,
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp()
      }, { merge: true });
    }

    // Seed Reservations
    for (const res of DEMO_RESERVATIONS) {
      await setDoc(doc(db, 'reservations', res.id), {
        ...res,
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp()
      });
    }

    // Seed Demo Retailer User Document
    await setDoc(doc(db, 'users', 'retailer_rewe_kleve'), {
      uid: 'retailer_rewe_kleve',
      name: 'Markus Weber',
      email: 'markus.weber@rewe-kleve.de',
      role: 'retailer',
      phone: '+49 2821 97810',
      language: 'de',
      createdAt: serverTimestamp(),
      updatedAt: serverTimestamp()
    });

    return { seeded: true, message: 'Successfully seeded Kleve demo stores and rescue products!' };
  } catch (error) {
    console.warn('Initial Firestore seeding skipped or pending connection:', error);
    return { seeded: false, message: error instanceof Error ? error.message : 'Seeding skipped' };
  }
}

/**
 * Forces re-seeding of all demo stores, products and reservations.
 */
export async function forceReSeedDemoData(): Promise<{ seeded: boolean; message: string }> {
  try {
    const freshProducts = getFreshDemoProducts();

    for (const store of DEMO_STORES) {
      await setDoc(doc(db, 'stores', store.id), {
        ...store,
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp()
      });
    }

    for (const product of freshProducts) {
      await setDoc(doc(db, 'products', product.id), {
        ...product,
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp()
      });
    }

    for (const res of DEMO_RESERVATIONS) {
      await setDoc(doc(db, 'reservations', res.id), {
        ...res,
        createdAt: serverTimestamp(),
        updatedAt: serverTimestamp()
      });
    }

    return { seeded: true, message: 'Successfully force-reseeded Kleve demo data!' };
  } catch (error) {
    console.error('Error force re-seeding:', error);
    return { seeded: false, message: error instanceof Error ? error.message : 'Unknown error' };
  }
}
